---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prod
    spec:
      containers:
        - name: prod
          # image: registry.digitalocean.com/kubeops-sgp-1/kubeops-node-prod:6f844c0
          image: registry.digitalocean.com/kubeops-sgp-1/kubeops-node-dev:6f844c0
          ports:
            - name: http
              containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi
