---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: prod-host
  namespace: ambassador
spec:
  hostname: www.wasuwat.online
  acmeProvider:
    email: wasuwatp18@gmail.com
  tlsSecret:
    name: tls2-cert
  requestPolicy:
    insecure:
      action: Redirect
      additionalPort: 8080