---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: stagging-host
  namespace: ambassador
spec:
  hostname: stagging.wasuwat.online
  acmeProvider:
    email: wasuwatp18@gmail.com
  tlsSecret:
    name: tls2-cert
  requestPolicy:
    insecure:
      action: Redirect
      additionalPort: 3000