---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stagging
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stagging
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stagging
    spec:
      containers:
        - name: stagging
          image: registry.digitalocean.com/kubeops-sgp-1/kubeops-node-stagging:c98fcbd
          ports:
            - name: http
              containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi
